# Site settings
title: Mayank Anand
email: mayank.96anand@gmail.com
description: Veeva Developer looking for opportunities in the field of Software Development.
baseurl: "/Anand_Mayank_website"
url: "https://mayank9614.github.io"
twitter_username: anand_offbeat
github_username: mayank9614

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Layout settings
layout: default

# Custom variables
css_file: /assets/css/main.css

# Other settings remain the same...