# Site settings
title: Mayank Anand
email: mayank.96anand@gmail.com
description: Veeva Developer looking for opportunities in the field of Software Development.
baseurl: "/Anand_Mayank_website"
url: "https://mayank9614.github.io/Anand_Mayank_website/"
twitter_username: anand_offbeat
github_username: mayank9614

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Layout settings
layout: home

# Navigation
header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md
  - contacts.md

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Skills
    url: /skills/
  - title: Contact
    url: /contacts/

# Social media profiles
social_links:
  twitter: anand_offbeat
  github: mayank9614
  linkedin: mayank-anand-11911469

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/